development:
  adapter: postgresql
  database: tweddit_development
  pool: 5
  timeout: 5000

test: &test
  adapter: postgresql
  database: tweddit_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: tweddit_production
  pool: 5
  timeout: 5000
